"""empty message

Revision ID: ae7788133784
Revises: d2560ccc5cd9
Create Date: 2016-02-17 04:03:46.611606

"""

# revision identifiers, used by Alembic.
revision = 'ae7788133784'
down_revision = 'd2560ccc5cd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_items', sa.Column('title', sa.String(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_items', 'title')
    ### end Alembic commands ###
