"""empty message

Revision ID: d2560ccc5cd9
Revises: 831e93ba27b9
Create Date: 2016-02-07 02:36:14.606818

"""

# revision identifiers, used by Alembic.
revision = 'd2560ccc5cd9'
down_revision = '831e93ba27b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_items',
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('lesson_plan', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_plan'], ['lesson_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_items')
    ### end Alembic commands ###
